function playTexture_PerGratingManual

global  screenPTR screenNum 

global Gtxtr   %Created in makeGratingTexture

%call configure file to preset Pstate - we're doing it this way so that we
%don't overwrite Pstate on the master and confuse stimulus modules and
%manual mappers
configPstate_PerGrating;


screenRes = Screen('Resolution',screenNum);


%define the list of parameters that can be accessed with the mouse and
%their settings
symbList = {'ori','s_freq','t_period','mask_radius','contrast','visible'};
valdom{1} = 0:15:359;
valdom{2} = logspace(log10(.01),log10(10),20);
valdom{3} = logspace(log10(.5),log10(10),20);  %Hz
valdom{3} = round(fliplr(screenRes.hz./valdom{3}));  %frames
valdom{4} = logspace(log10(.5),log10(60),20);
valdom{5} = [5 15 50 100];
valdom{6} = [0 1];

%set starting value and symbol 
state.valId = [7 10 5 8 4 2];  %Current index for each value domain
state.symId = 1;  %Current symbol index

%shorthand indices
vID=6; %visible

%update the parameters
for i = 1:length(valdom)-1
    symbol = symbList{i};
    val = valdom{i}(state.valId(i));
    updatePstate(symbol,num2str(val));
end
xsize = 2*valdom{4}(state.valId(4));  %width = 2*radius
ysize = xsize;
updatePstate('x_size',num2str(xsize));
updatePstate('y_size',num2str(ysize));


%initialize texture
makeTexture_PerGrating %this populates Gtxtr and Masktxtr

%initialize text
symbol = symbList{state.symId};
val = valdom{state.symId}(state.valId(state.symId));
newtext = [symbol ' ' num2str(val)];

%generate mask
stimsize=2*sqrt((xsize/2).^2+(ysize/2).^2); %this is the size of the grating generated by makeTexture
stimsizeN=deg2pix(stimsize,'round');
maskSize.height=4*stimsizeN; %make it large enough to cover rotated stimulus
maskSize.width=maskSize.height;
mask=makeMask(maskSize,round(maskSize.height/2),round(maskSize.height/2),...
    deg2pix(xsize,'round'),deg2pix(ysize,'round'),1,'none');
mtxtr = Screen(screenPTR, 'MakeTexture', mask,[],[],2); 
maskSrc=[0 0 maskSize.height maskSize.height];


%initialize screen
Screen(screenPTR, 'FillRect', 0.5)
Screen(screenPTR,'DrawText','ori 0',40,30,1);
Screen('Flip', screenPTR);


%mac and linux assign mouse buttons differently
if ismac
    leftB=[1 0 0];
    middleB=[0 0 1];
    rightB=[0 1 0];
else
    leftB=[1 0 0];
    middleB=[0 1 0];
    rightB=[0 0 1];
end

%start the actual loop
bLast = [0 0 0];
keyIsDown = 0;
TextrIdx = 1;
while ~keyIsDown
    
    [mx,my,b] = GetMouse(screenPTR);
    b=b(1:3);
    
    db = bLast - b; %'1' is a button release
           
    %%%Case 1: Left Button:  decrease value%%%
    if ~sum(abs(leftB-db))  
        
        symbol = symbList{state.symId};
        if state.valId(state.symId) > 1
            state.valId(state.symId) = state.valId(state.symId) - 1;
        elseif state.symId == 1
            state.valId(state.symId) = length(valdom{state.symId});
        end       
        
        val = valdom{state.symId}(state.valId(state.symId));
        
        if state.symId~=vID
            updatePstate(symbol,num2str(val));
        end
        
        newtext = [symbol ' ' num2str(val)];
        
        
        if strcmp(symbol,'mask_radius')
            %update size
            xsize = 2*valdom{4}(state.valId(4));  %width = 2*radius
            ysize = xsize;
            updatePstate('x_size',num2str(xsize));
            updatePstate('y_size',num2str(ysize));
            
            %generate new mask
            stimsize=2*sqrt((xsize/2).^2+(ysize/2).^2); %this is the size of the grating generated by makeTexture
            stimsizeN=deg2pix(stimsize,'round');
            maskSize.height=4*stimsizeN; %make it large enough to cover rotated stimulus
            maskSize.width=maskSize.height;
            mask=makeMask(maskSize,round(maskSize.height/2),round(maskSize.height/2),...
                 deg2pix(xsize,'round'),deg2pix(ysize,'round'),1,'none');
            mtxtr = Screen(screenPTR, 'MakeTexture', mask,[],[],2);
            maskSrc=[0 0 maskSize.height maskSize.height];
        end
        
        
        makeTexture_PerGrating
        TextrIdx = 1;               
    end
    
    %%%Case 2: Middle Button:  change parameter%%%
    if ~sum(abs(middleB-db))  % [0 0 1] is the scroll bar in the middle
        
        state.symId = state.symId+1; %update the symbol
        if state.symId > length(symbList)
            state.symId = 1; %unwrap
        end
        symbol = symbList{state.symId};
        val = valdom{state.symId}(state.valId(state.symId));
        
        
        newtext = [symbol ' ' num2str(val)];
        
        TextrIdx = 1;
    end
    
    %%%Case 3: Right Button: increase value%%%
    if ~sum(abs(rightB-db))  %  [0 1 0]  is right click
        
        symbol = symbList{state.symId};
        if state.valId(state.symId) < length(valdom{state.symId})
            state.valId(state.symId) = state.valId(state.symId) + 1;
        elseif state.symId == 1
            state.valId(state.symId) = 1;
        end
      
        val = valdom{state.symId}(state.valId(state.symId));        
        
        if state.symId~=vID
            updatePstate(symbol,num2str(val));
        end
            
        newtext = [symbol ' ' num2str(val)];
       
        
        if strcmp(symbol,'mask_radius')
            %update size
            xsize = 2*valdom{4}(state.valId(4));  %width = 2*radius
            ysize = xsize;
            updatePstate('x_size',num2str(xsize));
            updatePstate('y_size',num2str(ysize));
            
            %generate new mask
            stimsize=2*sqrt((xsize/2).^2+(ysize/2).^2); %this is the size of the grating generated by makeTexture
            stimsizeN=deg2pix(stimsize,'round');
            maskSize.height=4*stimsizeN; %make it large enough to cover rotated stimulus
            maskSize.width=maskSize.height;
            mask=makeMask(maskSize,round(maskSize.height/2),round(maskSize.height/2),...
                 deg2pix(xsize,'round'),deg2pix(ysize,'round'),1,'none');
            mtxtr = Screen(screenPTR, 'MakeTexture', mask,[],[],2);
            maskSrc=[0 0 maskSize.height maskSize.height];
        end
        
        TextrIdx = 1;
        
        makeTexture_PerGrating

    end
    
    TextrIdx = TextrIdx+1;
    
    %current grating parameters
    ori = valdom{1}(state.valId(1));
    contrast = valdom{5}(state.valId(5))/100*0.5;
    s_freq = valdom{2}(state.valId(2));
    t_period = valdom{3}(state.valId(3));
    
    %determine stimulus source coordinates (this generates the movement)
    pixpercycle=deg2pix(1/s_freq,'none');
    shiftperframe=pixpercycle/t_period;
    xoffset = mod((TextrIdx-1)*shiftperframe,pixpercycle);
    stimSrc=[xoffset 0 xoffset + stimsizeN-1 stimsizeN-1];
    
    %determine stimulus placement
    stimR=[0 0 stimsizeN-1 stimsizeN-1];
    stimDst = CenterRectOnPoint(stimR,mx,my);
    
    %determine mask placement
    maskDst=CenterRectOnPoint(maskSrc,mx,my);
    
    %only draw if visible
    if valdom{vID}(state.valId(vID))==1
        Screen('BlendFunction', screenPTR, GL_SRC_ALPHA, GL_ONE);
        Screen('DrawTexture', screenPTR, Gtxtr(1), stimSrc, stimDst,ori,[],contrast);
    
        %add mask
        Screen('BlendFunction', screenPTR, GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
        Screen('DrawTexture', screenPTR, mtxtr,maskSrc,maskDst);
    end
    
    %add text
    Screen(screenPTR,'DrawText',newtext,40,30,1);
    xypos = ['x ' num2str(mx) '; y ' num2str(my)];
    Screen(screenPTR,'DrawText',xypos,40,55,1);
    Screen('Flip', screenPTR);
    
    bLast = b;
    
    keyIsDown = KbCheck;
    
end



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Screen(screenPTR, 'FillRect', 0.5)
Screen(screenPTR, 'Flip');